### ISSUE TITLE
更新、削除は作成者以外ボタンが画面表示されなくなったけど、直接リクエストしたら作成者以外もできちゃうのでは？

### ISSUE THREAD

**Issue by itagakishintaro** [itagakishintaro/ProgressReport#37]

**Comment by uedatakeshi** [comment]
その通りで直リンクで編集可能です。
ということで編集の方はできないように修正しておきました。
削除はなんか、httpメソッドのDELETEとかauthenticity_tokenとか使ってて、テストできないので、未。

**Comment by itagakishintaro** [comment]
DELETEとかはcurlで叩けばOKです。
http://d.hatena.ne.jp/thata/20100207/1265554365

editメソッドに処理を入れるのではなく、privateメソッドに入れて、before actionでedit, destroyのときだけ呼ぶようにするのがベターだと思います。
