### ISSUE TITLE
一度ユーザー検索を行うと、ユーザー指定なしで検索ができない

### ISSUE THREAD

**Issue by cyberblack28** [itagakishintaro/ProgressReport#73]
ユーザー検索のプルダウンは、初回は「ユーザ選択」という項目があるが、一度ユーザーを選択して検索をすると2度目以降、「ユーザ選択」の項目がなくなり、全体での検索ができない。

**Comment by itagakishintaro** [comment]
https://github.com/activerecord-hackery/ransack/issues/119
