### ISSUE TITLE
投稿で画像と添付ファイルをアップできない

### ISSUE THREAD

**Issue by cyberblack28** [itagakishintaro/ProgressReport#74]
以下ログの内容です。

Started POST "/images" for 202.232.108.121 at 2015-09-17 12:25:50 +0900
Cannot render console from 202.232.108.121! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by ImagesController#create as JSON
  Parameters: {"file"=>#<ActionDispatch::Http::UploadedFile:0x007f6118845a50 @tempfile=#<Tempfile:/tmp/RackMultipart20150917-14440-1y5sptj.png>, @original_filename="tcp.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"file\"; filename=\"tcp.png\"\r\nContent-Type: image/png\r\n">, "content_type"=>"image/png", "user_id"=>"2"}
  User Load (2.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 2]]
Completed 500 Internal Server Error in 5ms

ArgumentError (string contains null byte):
  app/controllers/images_controller.rb:10:in `create'

  Rendered /home/pr-admin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_source.erb (3.5ms)
  Rendered /home/pr-admin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_trace.text.erb (0.7ms)
  Rendered /home/pr-admin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.text.erb (0.8ms)
  Rendered /home/pr-admin/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.text.erb (18.6ms)

**Comment by itagakishintaro** [comment]
原因

http://tkm9.hateblo.jp/entry/2015/02/17/210353

対策

railsを4.2.1にする

1. Gemfileでrails 4.2.1を指定
2. bundle update rails
3. bundle install
